### ISSUE TITLE
qt4: set default to -with-qt3support

### ISSUE THREAD

**Issue by guitorri** [cartr/homebrew-qt4#12]
Is it too much trouble to enable qt3support by default in the qt4 formula and bottles?

I know qt3support it was not enabled by default when the formula was in homebrew-core. 
It was however shipped in the official Qt binaries, which no longer work with macOS newer than 10.10.
Right now out Travis CI is at osx_image: xcode6.4 and pulling the official Qt .dmg to keep things running. 

I guess our project is the only one still stuck with qt3support... In this case I will have to fork your formula and make bottles myself until we get rid of qt3support.

**Comment by cartr** [comment]
I'd be happy to enable `-with-qt3support` by default, especially if that's how the official binaries shipped. Unfortunately, I don't currently have a way to rebuild bottles, so it may have to wait until that's solved.

Out of curiosity, do you know if it might be possible to create a separate formula for the `Qt3Support` module?

**Comment by guitorri** [comment]
Thank you for your positive response. I really don't know how to split Qt4 in multiple libs.

To solve my problem I made a bottle with --skip-relocate, extracted into `brew --prefix` and linked to have it working.

**Comment by cartr** [comment]
The latest revision of the formula now has Qt3Support enabled out of the box. Running `brew install qt@4` in your `.travis.yml` should install it for you.

Please let me know if it still isn't working, and feel free to file more issues if there's other functionality you'd like to see.
