### ISSUE TITLE
I'm not sure the bottle path is right for pyqt.

### ISSUE THREAD

**Issue by lloydc99** [cartr/homebrew-qt4#15]
executing command [brew install cartr/qt4/pyqt]
==> Installing pyqt from cartr/qt4
==> Downloading https://homebrew.bintray.com/bottles-qt4/pyqt-4.12.sierra.bottle
Error: Failed to download resource "pyqt"
Download failed: https://homebrew.bintray.com/bottles-qt4/pyqt-4.12.sierra.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.12/PyQt

**Comment by cartr** [comment]
It looks like I forgot to set the correct bottle path last time I rebuilt the PyQt bottle. Thanks for the bug report!

**Comment by lloydc99** [comment]
Thanks for the qt4 repo. I need it for ROS Indigo support!

**Comment by cartr** [comment]
Glad to hear you're getting some use out of my project! Please feel free to file more issues if you run into any other problems, or there's a package you'd like me to add or something.
