### ISSUE TITLE
Ostinato build on TravisCI failing

### ISSUE THREAD

**Issue by pstavirs** [cartr/homebrew-qt4#27]
This was working a month ago. 

Logs: https://travis-ci.org/pstavirs/ostinato/jobs/220604198

**Comment by cartr** [comment]
At the request of Homebrew maintainers, I changed the name of the Qt package from `qt` to `qt@4`. (The Homebrew people wanted to "reclaim" `qt` and use it for their Qt5 package.) I've filed [a Pull Request](https://github.com/pstavirs/ostinato/pull/214) on your repository that updates your .travis.yml to reflect this change.

Apologies for breaking your build.
