### ISSUE TITLE
fix Qt4 leopard and tiger builds

### ISSUE THREAD

**Issue by devernay** [cartr/homebrew-qt4#34]
Hi,

would you consider adding that patch (taken from tigerbrew) to allow building Qt4 on Leopard?
https://github.com/mistydemeo/tigerbrew/commit/fbda1798e96437da9268dcc9e5568aa45d60e474

also seen in https://trac.macports.org/ticket/43746

thanks again for maintaining this repo

**Comment by cartr** [comment]
Thanks for bringing this patch to my attention! I've made a [pull request](https://github.com/cartr/homebrew-qt4/pull/35) to add it to the formula. Could you please verify that it actually fixes the Leopard build?

**Comment by devernay** [comment]
I checked building on 10.12 from source with `g++-4.2 -mmacosx-version-min=10.5 -isysroot /Developer/SDKs/MacOSX10.5.sdk` with that patch, and I get a running Qt Designer.

I have no running 10.5 machine to test building on it, though.

I also submitted a set of patches to compile on Tiger (yes, I have a running Tiger machine - Leopard was just the first step to get there), and it runs fine!

Grab the patches in the zip file at https://github.com/mistydemeo/tigerbrew/issues/529

It doesn't affect the result when built on Leopard and newer (everything is ifdef'd)

**Comment by cartr** [comment]
@devernay I've added these patches to my pull request. Thanks!

**Comment by cartr** [comment]
I've given it some thought, and I don't think I'll be able to support Tiger or Leopard in this tap after all.

As discussed in @35, my `qt-webkit@2.3` formula would probably be nearly impossible to port to Tiger. I have no way to test Tiger or Leopard locally, so even if I could port it, I wouldn't be able to ensure future changes didn't break it. There's also no guarantee that mainline `brew` (or its formula syntax) will continue to support Leopard, especially given the Homebrew team's propensity for deprecations and backwards-incompatible changes.

Anyone who's interested in using Qt 4 on Tiger or Leopard should consider [MacPorts](https://www.macports.org/) or [Tigerbrew](https://github.com/mistydemeo/tigerbrew/) instead.
