### ISSUE TITLE
macdeployqt tool cannot find the qt plugins folder

### ISSUE THREAD

**Issue by samueljackson92** [cartr/homebrew-qt4#38]
This looks like it might be related to the changes in #25. When we try to run the `macdeployqt` tool to bundle our app it fails because it seems to assume that the qt plugins directory exists at `/usr/local/opt/qt@4/plugins` but it looks like the install path is set to `/usr/local/opt/qt@4/lib/qt4/plugins`.

Adding a symlink to the plugins directory in where the `macdeployqt` tool expects "fixed" it for us, but it would be nice to find a smarter solution.

**Comment by cartr** [comment]
Thanks for the report! The issue does indeed appear to be that the `macdeployqt` tool hard-codes the plugins directory as `qtPath + "/plugins"`. I'll try and write a patch to fix that.
