### ISSUE TITLE
Homebrew core renamed `python3` -> `python` and `python` -> `python@2`

### ISSUE THREAD

**Issue by megachweng** [cartr/homebrew-qt4#46]
`brew install python` will install python3 as default now.
`brew install pyqt@4 --with-python3` only build python3 library
so I can't import PyQt4 in python2, there is only `Python3.6/site-packages` in `'/usr/local/Cellar/pyqt@4/4.12.1/lib/` directory

please fix it.

**Comment by cartr** [comment]
Thank you for the report! I'll try and get this fixed ASAP.

**Comment by cartr** [comment]
Should be fixed now -- please run `brew update && brew upgrade` and try reinstalling `pyqt@4`.

**Comment by megachweng** [comment]
works like a charm!!
PS: I've noticed that option `--with-python3` have changed to `--with-python`. I think the first one is less confused.
