### ISSUE TITLE
Yosemite bottles

### ISSUE THREAD

**Issue by albertosottile** [cartr/homebrew-qt4#48]
I am getting this error when I try to install PySide 1.2 on Yosemite (Travis CI xcode6.4):
```
==> Installing cartr/qt4/pyside@1.2 dependency: cartr/qt4/shiboken@1.2
==> Downloading https://dl.bintray.com/cartr/autobottle-qt4/shiboken@1.2-1.2.2_2
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "shiboken@1.2"
Download failed: https://dl.bintray.com/cartr/autobottle-qt4/shiboken@1.2-1.2.2_2.yosemite.bottle.2.tar.gz
```

Is this a temporary issue with bintray/akamai or are you removing bottles for Yosemite? 
Thanks

**Comment by cartr** [comment]
Bottles are currently broken for all platforms, not just Yosemite. (I pushed out [an urgent fix](https://github.com/cartr/homebrew-qt4/pull/47) last night and haven't had time to rebuild the bottles yet.) When I do build the bottles, I'll make sure and build them for Yosemite.

Apologies for the inconvenience.

**Comment by albertosottile** [comment]
I apologize, I did not know that the renaming to python@2 in the recipes required a complete rebuild of the bottles. in fact, we [successfully packed](https://travis-ci.org/Syncplay/syncplay/builds/348652214) our software yesterday using the new homebrew recipe and the old bottles (before your fix). I will wait for updated bottles then. Thanks for all this work.
