### ISSUE TITLE
MacOS.prefer_64_bit? has been deprecated in Homebrew so the formula now fails to install

### ISSUE THREAD

**Issue by LoganTutt** [cartr/homebrew-qt4#65]
The following line causes a `MethodDeprecationError` when `brew upgrade` is run due to the deprecation of the method in Homebrew core.  
https://github.com/cartr/homebrew-qt4/blob/af62582a6970391c6d8f6009c3dc16bcc3caa5b1/qt%404.rb#L129

The relevant Pull Request in Homebrew can be seen here: https://github.com/Homebrew/brew/pull/5519

**Comment by cartr** [comment]
Thanks for the report! I've removed this call from the formula source code.
