### ISSUE TITLE
brew tap-pin cartr/qt4  failed

### ISSUE THREAD

**Issue by skfly007** [cartr/homebrew-qt4#69]
skfly@skflydeMacBook-Pro ~ % brew tap-pin cartr/qt4
Error: Calling brew tap-pin user/tap is disabled! Use fully-scoped user/tap/formula naming instead.

**Comment by cartr** [comment]
Thanks for reporting this! Can you try running `brew install cartr/qt4/qt@4` instead? (If that works, I'll update the README.)

**Comment by skfly007** [comment]
I just run `brew install qt@4` and it works?
what's the reason of this situation?

skfly@skflydeMacBook-Pro ~ % brew tap-pin cartr/qt4
Error: Calling brew tap-pin user/tap is disabled! Use fully-scoped user/tap/formula naming instead.
skfly@skflydeMacBook-Pro ~ % brew install qt@4
==> Installing qt@4 from cartr/qt4
==> Installing dependencies for cartr/qt4/qt@4: openssl@1.0
==> Installing cartr/qt4/qt@4 dependency: openssl@1.0
==> Downloading https://dl.bintray.com/cartr/autobottle-qt4/openssl@1.0-1.0.2t.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/faa8d3dc06601237a6f42a93ec6d8b0229426f01ea109e3
#########################################                                 58.2%

**Comment by skfly007** [comment]
I from china and using a mirror for home-brew. 

```
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles

```

**Comment by cartr** [comment]
@hnsxcxwpf2 Ah, it looks like when you run `brew install qt@4`, Homebrew automatically searches through all your taps for a formula called `qt@4`. (I don't think they did that when I first created this project, but I could be mistaken.) So you don't need to run `brew tap-pin` anymore. I'll fix the README!
