### ISSUE TITLE
bintray is going away. Distribute bottles through github or another service?

### ISSUE THREAD

**Issue by devernay** [cartr/homebrew-qt4#71]
I just saw that bintray will soon go away, will there be another way to distribute bottles? Maybe use github binary release assets?
Also, can we contribute 
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by cartr** [comment]
Thanks for letting me know about this!

To be honest, I'm not sure I want to continue maintaining this tap. Working with Homebrew is kind of obnoxious, and I no longer have access to all the test hardware and OS installs I used to use. Plus, the _Hello World!_ software package -- the original reason I started this tap -- is now using a non-Homebrew copy of Qt 5.

Would you be up for taking over maintainership? You've been really helpful in the past, so I'd be happy to give you commit access or transfer the repo to you or something.

**Comment by jinhyoo** [comment]
Bintray is officially shut down and it seems that installing PyQt4 is broken.

**Comment by cartr** [comment]
Apologies for the delay! I've pushed a change that should resolve this by moving the bottles from BinTray to GitHub Releases.

There are still some broken bottle links, for more obscure packages that I never rebuilt/migrated off the bottles Homebrew originally shipped for them. Please let me know if you'd like me to fix any of these, or if installing PyQt4 is still broken.

**Comment by jinhyoo** [comment]
Thanks for the quick turnaround! It looks like openssl, which pyqt depends on, is still using bintray.

**Comment by cartr** [comment]
@jinhyoo Good catch! I'd forgotten to clear my cache before testing the change. The remaining packages should be fixed.

**Comment by devernay** [comment]
We could also switch to using the system's openssl, we have a patch:  https://github.com/macports/macports-ports/blob/master/aqua/qt4-mac/files/patch-qt4-openssl111.diff
