### ISSUE TITLE
warning when installing ncurses on mac 11.2.3

### ISSUE THREAD

**Issue by eva-barczykowska** [cartr/homebrew-qt4#74]
ewabarczykowska@mac ~ % brew install ncurses
Warning: ncurses 6.2 is already installed and up-to-date.
To reinstall 6.2, run:
  brew reinstall ncurses
ewabarczykowska@mac ~ % brew reinstall ncurses
==> Downloading https://ghcr.io/v2/homebrew/core/ncurses/manifests/6.2
Already downloaded: /Users/ewabarczykowska/Library/Caches/Homebrew/downloads/b365b9504480dc3ed1cc0e4c0970fb1defdb8e00a9dcd691c8dde55706880ef4--ncurses-6.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/ncurses/blobs/sha256:b34b4aa433f23405c6104bf810836eed2686f11c660b8668a7af86f99be2329f
Already downloaded: /Users/ewabarczykowska/Library/Caches/Homebrew/downloads/82e0a72603867eb866854cfde4fa3c215351a567f5ce2d6fdb78434aa7bfae43--ncurses--6.2.big_sur.bottle.tar.gz
==> Reinstalling ncurses 
==> Pouring ncurses--6.2.big_sur.bottle.tar.gz
==> Caveats
ncurses is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have ncurses first in your PATH, run:
  echo 'export PATH="/usr/local/opt/ncurses/bin:$PATH"' >> ~/.zshrc

For compilers to find ncurses you may need to set:
  export LDFLAGS="-L/usr/local/opt/ncurses/lib"
  export CPPFLAGS="-I/usr/local/opt/ncurses/include"

For pkg-config to find ncurses you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/ncurses/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/ncurses/6.2: 3,913 files, 8.9MB
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/qt@4.rb:204

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/qt@4.rb:205

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the wix/brew tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:12

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the wix/brew tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:13

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the wix/brew tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:14

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the wix/brew tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:15

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the wix/brew tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:16

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the wix/brew tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:17

Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the facebook/fb tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/facebook/homebrew-fb/idb-companion.rb:19

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the facebook/fb tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/facebook/homebrew-fb/idb-companion.rb:20

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/openssl@1.0.rb:11

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/openssl@1.0.rb:12

ewabarczykowska@mac ~ %

**Comment by cartr** [comment]
Thank you for your report! We actually already have a PR open to resolve this issue (thanks to a third-party contributor), which I will try and get tested/out tomorrow: https://github.com/cartr/homebrew-qt4/pull/73. In the short term, this shouldn't affect your use of Homebrew at all, beyond printing annoying warning messages a lot.

Unfortunately Homebrew really likes to do this kind of thing where they change minor details of the formula syntax for no reason whatsoever, then tell users to bug maintainers like me to "fix" our perfectly-fine tap code. If you don't want them to do this, you could consider filing a ticket on https://github.com/Homebrew/brew, opening a discussion on https://github.com/Homebrew/discussions/discussions, or contacting the Homebrew core team some other way.

**Comment by cartr** [comment]
This should now be fixed the next time you run `brew update`. Please let me know if you see the warning message again!
