### ISSUE TITLE
brew install cartr/qt4/pyqt fails on MacOs Monterey

### ISSUE THREAD

**Issue by mackdad42** [cartr/homebrew-qt4#78]
Just started downloading new programs for a new lab IMac with MacOs Monterey and I'm trying to install pyqt for a secondary program. 

Below I've copied and pasted the error output I'm given when I run the following command: brew install cartr/qt4/pyqt

I'm relatively new to computers, so I don't quite understand what's going wrong here. If anyone can help troubleshoot this, I'd greatly appreciate it. 

Thanks! 

Last 15 lines from /Users/mackenzieleavitt/Library/Logs/Homebrew/openssl@1.0/03.make:
 ^
x86_64cpuid.s:273:10: error: unknown token in expression
 cmpq $0,%rax
         ^
x86_64cpuid.s:273:10: error: invalid operand
 cmpq $0,%rax
         ^
x86_64cpuid.s:274:9: error: unknown token in expression
 cmoveq %rcx,%rax
        ^
x86_64cpuid.s:274:9: error: invalid operand
 cmoveq %rcx,%rax
        ^
make[1]: *** [x86_64cpuid.o] Error 1
make: *** [build_crypto] Error 1

**Comment by sho-he** [comment]
@mackdad42 

Hello.
Is it settled?
I have same error in my m1 mac.
If you have solution of this problems, I want you to share it.
 best regards.

**Comment by Leo-MathGuy** [comment]
Same error

**Comment by Leo-MathGuy** [comment]
Solved by following https://stackoverflow.com/questions/64951024/how-can-i-run-two-isolated-installations-of-homebrew and installing from alternate brew

**Comment by cartr** [comment]
This is probably the same issue as #86.
