### ISSUE TITLE
brew tap fails with invalid formula due to disabled bottle :unneeded

### ISSUE THREAD

**Issue by eli-schwartz** [cartr/homebrew-qt4#81]
https://github.com/cartr/homebrew-qt4/blob/aa161cdc9666b6718999c70d6e6e7e638181ed45/treeline.rb#L8
https://github.com/cartr/homebrew-qt4/blob/aa161cdc9666b6718999c70d6e6e7e638181ed45/qbzr.rb#L8

This becomes invalid in https://github.com/Homebrew/brew/pull/12259 and as a result it is no longer possible to tap this brew.

The following error is produced:
```
==> Tapping cartr/qt4
Cloning into '/usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4'...
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/treeline.rb
treeline: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/treeline.rb:8

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/qbzr.rb
qbzr: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/qbzr.rb:8

Error: Cannot tap cartr/qt4: invalid syntax in tap!
```

Found in https://github.com/mesonbuild/meson/runs/5504514413?check_suite_focus=true#step:6:1

**Comment by cartr** [comment]
Thank you for reporting this issue! 

I don't currently have access to a Mac to test changes to this tap. Is there any chance you could submit a Pull Request with the needed changes? 

On Thu, Mar 10, 2022, at 5:06 PM, Eli Schwartz wrote:
> 
> 
> 
> https://github.com/cartr/homebrew-qt4/blob/aa161cdc9666b6718999c70d6e6e7e638181ed45/treeline.rb#L8
> https://github.com/cartr/homebrew-qt4/blob/aa161cdc9666b6718999c70d6e6e7e638181ed45/qbzr.rb#L8
> 
> This becomes invalid in Homebrew/brew#12259 <https://github.com/Homebrew/brew/pull/12259> and as a result it is no longer possible to tap this brew.
> 
> The following error is produced:
> 
> `==> Tapping cartr/qt4
> Cloning into '/usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4'...
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/treeline.rb
> treeline: Calling bottle :unneeded is disabled! There is no replacement.
> Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core):
>   /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/treeline.rb:8
> 
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/qbzr.rb
> qbzr: Calling bottle :unneeded is disabled! There is no replacement.
> Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core):
>   /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/qbzr.rb:8
> 
> Error: Cannot tap cartr/qt4: invalid syntax in tap!
`

**Comment by eli-schwartz** [comment]
Sadly, I don't use macOS except in the sense that a project I work on has macOS CI which someone else set up. So I cannot test it either. :(

(I can do a lot of investigative work and digging to find the cause of the problem, but that's about my limit. I'm not even sure I fully understand what this formula statement does.)

Based on following links from that ticket and https://github.com/Homebrew/brew/pull/12913 to other projects encountering the same issue and seeing how they resolved it, simply removing those lines may be the right solution.

**Comment by eli-schwartz** [comment]
Alright, I tried to test this out by removing those lines and pointing the Meson CI at my fork, results are here: https://github.com/eli-schwartz/meson/runs/5513240977?check_suite_focus=true

The error is gone, qt4 is successfully installed and the CI that tries to build a program against Qt4 now passes.

My hope is that that means my fix is correct. :D
