### ISSUE TITLE
MacOS M1 error installation

### ISSUE THREAD

**Issue by irinatu** [cartr/homebrew-qt4#84]
can not install on the MacOS v12.4 M1 architecture :
==> Installing cartr/qt4/qt@4 dependency: openssl@1.0
==> perl ./Configure --prefix=/opt/homebrew/Cellar/openssl@1.0/1.0.2t --openssldir=/opt/homebrew/etc/openssl no-ssl2 no-ssl3 no-zlib shared enable-cms darwin64-x86_64-cc enable-ec_nistp_64_gcc_128
==> make depend
==> make
Last 15 lines from /Users/ituszynska/Library/Logs/Homebrew/openssl@1.0/03.make:
 ^
x86_64cpuid.s:273:10: error: unknown token in expression
 cmpq $0,%rax
         ^
x86_64cpuid.s:273:10: error: invalid operand
 cmpq $0,%rax
         ^
x86_64cpuid.s:274:9: error: unknown token in expression
 cmoveq %rcx,%rax
        ^
x86_64cpuid.s:274:9: error: invalid operand
 cmoveq %rcx,%rax
        ^
make[1]: *** [x86_64cpuid.o] Error 1
make: *** [build_crypto] Error 1

**Comment by rahim** [comment]
I'm also seeing the above, also MacOS v12.4 ARM M1.

**Comment by mc-introhive** [comment]
https://github.com/cartr/homebrew-qt4/issues/83#issuecomment-1187845142

**Comment by okachobi** [comment]
Same issue- seems the OpenSSL 1.0 dependency code is intel-specific or something.  However, the tap nutcracker/tap/openssl@1.0 compiles properly, but I can't determine how to force this qt4 tap to use it instead.  I get an error:

```
Error: Formulae found in multiple taps:
       * nutcracker/tap/openssl@1.0
       * cartr/qt4/openssl@1.0
 
 Please use the fully-qualified name (e.g. nutcracker/tap/openssl@1.0) to refer to the formula.
 
```

**Comment by Leo-MathGuy** [comment]
Solved by following https://stackoverflow.com/questions/64951024/how-can-i-run-two-isolated-installations-of-homebrew and installing from alternate brew

**Comment by cartr** [comment]
This is probably the same issue as #86.
