### ISSUE TITLE
brew install cartr/qt4/qt@4 in Apple M1 Pro machine ,  make error, please help!

### ISSUE THREAD

**Issue by emorasoul** [cartr/homebrew-qt4#85]
machine:
MacBook Pro   Apple M1 Pro
macOS monterey 12.6.1 

when i install qt4 with:
brew install cartr/qt4/qt@4

error as follow:

==> Applying qt4-bigsur.patch
patching file src/3rdparty/javascriptcore/JavaScriptCore/jit/JITStubs.cpp
==> mv src/3rdparty/javascriptcore/VERSION src/3rdparty/javascriptcore/VERSION.md
==> ./configure -prefix /opt/homebrew/Cellar/qt@4/4.8.7_6 -plugindir /opt/homebrew/Cellar/qt@4/4.8.7_6/lib/qt4/plugins -importdir /opt/homebrew/Cellar/qt@4
==> make
Last 15 lines from /Users/icsl/Library/Logs/Homebrew/qt@4/03.make:
make[2]: *** [.obj/release-shared/qtconcurrentresultstore.o] Error 1
2 errors generated.
make[2]: *** [.obj/release-shared/qtconcurrentthreadengine.o] Error 1
2 errors generated.
make[2]: *** [.obj/release-shared/qtconcurrentiteratekernel.o] Error 1
2 errors generated.
make[2]: *** [.obj/release-shared/qthreadpool.o] Error 1
2 errors generated.
make[2]: *** [.obj/release-shared/qlocale_mac.o] Error 1
2 errors generated.
make[2]: *** [.obj/release-shared/qlibraryinfo.o] Error 1
2 errors generated.
make[2]: *** [.obj/release-shared/qglobal.o] Error 1
make[1]: *** [release] Error 2
make: *** [sub-corelib-make_default-ordered] Error 2

error in log:
...
In file included from ../../include/QtCore/qatomic_macosx.h:1:
In file included from ../../include/QtCore/../../src/corelib/arch/qatomic_macosx.h:52:
In file included from ../../include/QtCore/qatomic_powerpc.h:1:
../../include/QtCore/../../src/corelib/arch/qatomic_powerpc.h:126:36: error: invalid output constraint '=&b' in asm
                 : [originalValue] "=&b" (originalValue),
                                   ^
../../include/QtCore/../../src/corelib/arch/qatomic_powerpc.h:143:36: error: invalid output constraint '=&b' in asm
                 : [originalValue] "=&b" (originalValue),
                                   ^
2 errors generated.
2 errors generated.
make[2]: *** [.obj/release-shared/qfuturewatcher.o] Error 1
make[2]: *** [.obj/release-shared/qtconcurrentresultstore.o] Error 1
...

**Comment by cartr** [comment]
This is probably the same issue as #86.
