### ISSUE TITLE
"brew install qt@4" doesn't work on Apple Silicon

### ISSUE THREAD

**Issue by rnrdave** [cartr/homebrew-qt4#86]
Apple chip M1
OS Ventura Version 13.5.2 (22G91)

xxx@xxx-MacBook-Pro build % brew install qt@4
==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################################################################## 100.0%
==> Fetching dependencies for cartr/qt4/qt@4: cartr/qt4/openssl@1.0
==> Fetching cartr/qt4/openssl@1.0
==> Downloading https://www.openssl.org/source/openssl-1.0.2t.tar.gz
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/5d2da6a9ed1a20ef9d1b1418d79aa674cf5577b70ca1ce436fdaadfa04f0429c--openssl-1.0.2t.tar.gz
==> Fetching cartr/qt4/qt@4
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/480b7142c4e2ae07de6028f672695eb927a34875/qt/el-capitan.patch
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/270f37555cc0fbcbfcb79029d20314a8a9deb19ece6e0d65bcc07c06f39fb1c4--el-capitan.patch
==> Downloading https://raw.githubusercontent.com/cartr/homebrew-qt4/41669527a2aac6aeb8a5eeb58f440d3f3498910a/patches/qsetting-nulls.patc
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/d7c1bbff5bb49984edc759c847ff95dc0b4f55d49af35dd73fa39a4da7f0615b--qsetting-nulls.patch
==> Downloading https://raw.githubusercontent.com/cartr/homebrew-qt4/c957b2d755c762b77142e35f68cddd7f0986bc7b/patches/qt4-versions-withou
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/d7d2e2382dc769bf0ece645f65eb8b4f693c39a65df2aee2d98e2295c5e35fa4--qt4-versions-without-underscores.patch
==> Downloading https://raw.githubusercontent.com/cartr/homebrew-qt4/c957b2d755c762b77142e35f68cddd7f0986bc7b/patches/linguist-findmessag
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/dcdcfd0e95f312ec1eb80ad08a5e5442f9b6441866e1a21f14540dfeda19983a--linguist-findmessage-null-check.patch
==> Downloading https://raw.githubusercontent.com/cartr/homebrew-qt4/22a6e328b6d911b3c1cedcaadb2882dda728f8a7/patches/qfixed.patch
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/7834bea5f7d65470477e6495da12abc5756e0852999972e2eab3382801f2c183--qfixed.patch
==> Downloading https://raw.githubusercontent.com/cartr/homebrew-qt4/b7bc7818aa11c809209032554a990b1cef7edacc/patches/qobject-spurious-wa
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/b25e8f0795d7573e60de0730baabf5de4db694db961d326730a0547d8479c34a--qobject-spurious-warnings.patch
==> Downloading https://raw.githubusercontent.com/cartr/homebrew-qt4/98a906e1ad47106c65021150938de61138799ea8/patches/qt4-bigsur.patch
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/4009dd43aeff8eea0ffd4c00f0f82bc82a3b4d5107de6199c4b6e914f5cfc0fd--qt4-bigsur.patch
==> Cloning https://gist.github.com/tdsmith/f55e7e69ae174b5b5a03.git
Updating /Users/david/Library/Caches/Homebrew/qt@4--test-project--git
==> Checking out revision 6f565390395a0259fa85fdd3a4f1968ebcd1cc7d
HEAD is now at 6f56539 
HEAD is now at 6f56539
==> Downloading https://download.qt.io/archive/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/318c6ec9195279fc4b0c34f9ac17e903cbb18bf09d8223e01d48ddfeb0b43f0c--qt-everywhere-opensource-src-4.8.7.tar.gz
==> Installing qt@4 from cartr/qt4
==> Installing dependencies for cartr/qt4/qt@4: cartr/qt4/openssl@1.0
==> Installing cartr/qt4/qt@4 dependency: cartr/qt4/openssl@1.0
==> perl ./Configure --prefix=/opt/homebrew/Cellar/openssl@1.0/1.0.2t --openssldir=/opt/homebrew/etc/openssl no-ssl2 no-ssl3 no-zlib shar
==> make depend
==> make
Last 15 lines from /Users/david/Library/Logs/Homebrew/openssl@1.0/03.make:
 ^
x86_64cpuid.s:273:10: error: unknown token in expression
 cmpq $0,%rax
         ^
x86_64cpuid.s:273:10: error: invalid operand
 cmpq $0,%rax
         ^
x86_64cpuid.s:274:9: error: unknown token in expression
 cmoveq %rcx,%rax
        ^
x86_64cpuid.s:274:9: error: invalid operand
 cmoveq %rcx,%rax
        ^
make[1]: *** [x86_64cpuid.o] Error 1
make: *** [build_crypto] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/cartr/homebrew-qt4/issues

**Comment by Leo-MathGuy** [comment]
Same issue

**Comment by Leo-MathGuy** [comment]
Solved by following https://stackoverflow.com/questions/64951024/how-can-i-run-two-isolated-installations-of-homebrew and installing from alternate brew

**Comment by cartr** [comment]
Thanks! I've added that workaround to the README.
